### ISSUE TITLE
missing orientation warning for parking:left/right=no

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/osm-tag-updater#11]
There is still a warning for missing orientation value if there is no parking on one side.

E.g. deprecated input...
```
parking:condition:left=free
parking:lane:left:parallel=on_street
parking:lane:left=parallel
parking:lane:right=no_stopping
```
...throws a warning - obviously because the tool expects an orientation key for the right side.

**Comment by SupaplexOSM** [comment]
(but parking:both=no works fine now.)

**Comment by SupaplexOSM** [comment]
Addition: This issue also applies to value `separate`.

So if `parking:left` or `parking:right` are either `no` or `separate`, the tool should not expect an orientation key for this side.

**Comment by tordans** [comment]
Danke! Ich hoffe, das ist in 0.0.19 gleich behoben.
