### ISSUE TITLE
List of all tag transformations > 404

### ISSUE THREAD

**Issue by Discostu36** [osmberlin/osm-tag-updater#12]
The link to "list of all tag transformations" at the bottom of https://osmberlin.github.io/osm-tag-updater leads to a 404 error.

**Comment by SupaplexOSM** [comment]
Strange, I can't confirm this. For me, a list opens (Ubuntu 18.04 + Firefox 107)... @tordans - any ideas?

**Comment by Discostu36** [comment]
I also can't reproduce it anymore 🤔

**Comment by Discostu36** [comment]
https://osmberlin.github.io/list is the URL that was opened. It is actually the link that is there in the href. There seems to be a JavaScript that catches the click event and opens https://osmberlin.github.io/osm-tag-updater/#/list instead?

**Comment by tordans** [comment]
Danke! Ich denke, dass ist in 0.0.19 gleich behoben. Sonst bitte erneut melden/öffnen!

**Comment by Discostu36** [comment]
Tritt bei Öffnen in neuem Tab immer noch auf

**Comment by tordans** [comment]
I gave it another go. The footer link should work by regular click + right click => "open in new tab" now. Unfortunately shift/cm+click does not open in new tab/window due to the workaround.
I applied the workaround only to the footer, not the links on https://osmberlin.github.io/osm-tag-updater/
