### ISSUE TITLE
New parking scheme tags end up with fixme output

### ISSUE THREAD

**Issue by davidpnewton** [osmberlin/osm-tag-updater#14]
As an experiment I added the new parking scheme tags to way 1034849173 to see what would happen when the tag updater code came across them. I left the old scheme tags in place as well. The result is invalid output from the updater.

I would have expected the old scheme tags to be flagged with transformation information provided. That did indeed occur. However I would also have expected new scheme tags to be ignored because they are already present and valid. What instead happened was that the new scheme tags were parsed and highlighted with fixme messages and the instruction was to fix them manually.

New scheme tags when present should either be completely ignored or highlighted as being compatible with the new scheme.

**Comment by tordans** [comment]
> New scheme tags when present should either be completely ignored or highlighted as being compatible with the new scheme.

Sounds reasonable; will have a look in the weeks to come.

**Comment by tordans** [comment]
I improved this in https://github.com/osmberlin/osm-tag-updater/commit/bb5e5164a5a1819ea208c91c8b7d8b606802334b

> When new+old schema is mixed, the new is ignored + notice
>When input has both the old and the new schema…
>- the app will only transpose the old schema
>- there is a notice about the new schema being present
>- but no auto-merge of new and old

@davidpnewton @SupaplexOSM please have a look and report back if there are other / new issues. Thanks!
