### ISSUE TITLE
Typos and phraseology improvements

### ISSUE THREAD

**Issue by davidpnewton** [osmberlin/osm-tag-updater#15]
Please find details of some typos on the site for fixing and some phraseology improvement suggestions.

- "FYI, it looks like this way has already new tags tagged. Please merge them manually in your editor of choise:" should read choice at the end and has already should be already has
- "Also consider checking the actual parking situation on aerial imagery and streetlevel images to make sure nothing change since this road segment was mapped" should be street-level
- "Please provide the position of parked cars. This information was not recored previously, which is one of the benefits of the new schema." should read recorded rather than recored.

**Comment by tordans** [comment]
Thanks @davidpnewton, fixed.

In case new typos show up – which is likely :) – it would be great to have a old-text > new-text version in the issue, so I can copy the whole thing. (But search for the old thing.) That would reduce work and make sure I don't make new mistakes :).
