### ISSUE TITLE
typo "Tags that where ignored" --> "Tags that were ignored"

### ISSUE THREAD

**Issue by legofahrrad** [osmberlin/osm-tag-updater#16]
![grafik](https://user-images.githubusercontent.com/92865620/215353605-1eedcfd4-8729-424f-8976-7ca36e25a57f.png)

~where~ should be **were**

---
I'm not sure where this is in the code, so I couldn't create a PR. Maybe someone else knows ;)

**Comment by tordans** [comment]
Thanks @legofahrrad, this is fixed now.
