### ISSUE TITLE
Add general advice to proof the results

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/osm-tag-updater#4]
Maybe add a general note on the top of the page or near the output to make users aware of proofing the results?

> Parking lane tagging is complex and difficult and especially was in the past. Tagging mistakes, inconsistencies or missinterpretations were common in particular when tagging parking restrictions. Please check the results for plausibility and whether they are up-to-date!

**Comment by SupaplexOSM** [comment]
Automated Edits code of conduct (see #6) could be linked in such a notice.

**Comment by tordans** [comment]
Thanks! Added in 0.0.8; UI will change a bit soon, though.
