### ISSUE TITLE
Support deprecated parking:condition "time_interval/default" schema

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/osm-tag-updater#5]
One year ago, there already was a first proposal to introduce conditional-Tagging for parking conditions. But old data are still very common. It would be nice to deal with the most common tags:

`parking:condition:{SIDE}`
`parking:condition:{SIDE}:time_interval`
`parking:condition:{SIDE}:default`.

This can be translated to:

`parking:condition:{SIDE}` + `parking:condition:{SIDE}:time_interval = $TIME_INTERVAL`
➔ `parking:{SIDE}:...:conditional = ... @ ($TIME_INTERVAL)` according to our table. Both tags need to be present at the same time.

`parking:condition:{SIDE}:default`
➔ `parking:{SIDE}:...` according to our table. If it's unspecified, we just skip it.

---

`parking:condition:{SIDE}:2:*`, `parking:condition:{SIDE}:3:*` etc. were documented and are in use to tag multiple restrictions (see examples below). All their meanings can be added to the output list or - if there are multiple values for the same keys, they need to be merged in the same conditional string separated by a semicolon + space (`"; "`). But that's rather nice to have for now.

**Comment by SupaplexOSM** [comment]
[Example 1](https://www.openstreetmap.org/way/307759170):

`parking:condition:right = ticket` +
`parking:condition:right:default = free` +
`parking:condition:right:time_interval = Mo-Fr 09:00-20:00;Sa 09:00-18:00`
➔
`parking:right:fee = no` +
`parking:right:fee:conditional = yes @ (Mo-Fr 09:00-20:00;Sa 09:00-18:00)`


[Example 2](https://www.openstreetmap.org/way/71282503):

`parking:condition:right = loading` +
`parking:condition:right:default = no_stopping` +
`parking:condition:right:time_interval = Mo-Fr 09:00-14:00`
➔
`parking:right:restriction = no_stopping` +
`parking:right:restriction:conditional = loading_only @ (Mo-Fr 09:00-14:00)`

---

_Just for the case we plan to support "multi-level" old tags:_

[Multi-level example 1](https://www.openstreetmap.org/way/294268851):

`parking:condition:right = ticket` +
`parking:condition:right:time_interval = Mo-Fr 09:00-20:00;Sa 09:00-18:00` +
`parking:condition:right:default = free` +
`parking:condition:right:2 = no_stopping` +
`parking:condition:right:2:time_interval = Mo-Fr 06:00-14:00`
➔
`parking:right:fee = no` +
`parking:right:fee:conditional = yes @ (Mo-Fr 09:00-20:00;Sa 09:00-18:00)` +
`parking:right:restriction:conditional = no_stopping @ (Mo-Fr 06:00-14:00)`


[Multi-level example 2](https://www.openstreetmap.org/way/303514551):

`parking:condition:right = no_parking` +
`parking:condition:right:time_interval = Mo-Su 08:00-16:00` +
`parking:condition:right:2 = no_stopping` +
`parking:condition:right:2:time_interval = Mo-Su 07:00-08:00,16:00-19:00` +
`parking:condition:right:3 = free` +
`parking:condition:right:3:time_interval = Mo-Su 19:00-07:00`
➔
`parking:right:restriction:conditional = no_parking @ (Mo-Su 08:00-16:00); no_stopping @ (Mo-Su 07:00-08:00,16:00-19:00)`  +
`parking:right:fee = no @ (Mo-Su 19:00-07:00)` (Note: This is bad tagging, since "fee=no" should be just the default...)

**Comment by tordans** [comment]
@SupaplexOSM I don't think I will find time to add this kind of complex transformation. 

Is there maybe a page that we can link to, based on some key?
Eg, I could show a message whenever `:2` or `:3` or `:default` or `:time_interval` is present in the key and link to somewhere.

**Comment by SupaplexOSM** [comment]
Maybe we/somebody can implement it later.

I created a page that describes how to transform this kind of tagging: https://wiki.openstreetmap.org/wiki/Street_parking/Translating_deprecated_default_and_time_interval_tagging

Can you link on it in a warning message?

**Comment by tordans** [comment]
0.0.9 will show a message with link to this wiki page. Thank you!
