### ISSUE TITLE
Translations with 'regex' compare type still are listed in "could not be transposed" list

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/osm-tag-updater#8]
Inputs that are translated with the 'regex' compare type (i.e. conditional restrictions) are correctly translated to the output, but are still listed in the "Tags that could not be transposed automatically" list.

Example Input:
`parking:condition:right:conditional=no_stopping @ (Mo-Fr)`

**Comment by tordans** [comment]
Danke. Ist in der nächsten Version gefixt (0.0.8)
